// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

function Counter(props) {
  var onDelete = props.onDelete;
  var onDecrement = props.onDecrement;
  var onIncrement = props.onIncrement;
  var counter = props.counter;
  var formatCount = function (param) {
    if (counter.value === 0) {
      return "Zero";
    } else {
      return counter.value.toString();
    }
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("span", {
                                  children: formatCount(undefined),
                                  className: "badge m-2 badge-" + (
                                    counter.value === 0 ? "warning" : "primary"
                                  ),
                                  style: {
                                    fontSize: "24px"
                                  }
                                }),
                            className: ""
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx("i", {
                                          "aria-hidden": true,
                                          className: "fa fa-plus-circle"
                                        }),
                                    className: "btn btn-secondary",
                                    onClick: (function (param) {
                                        Curry._1(onIncrement, counter);
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx("i", {
                                          "aria-hidden": true,
                                          className: "fa fa-minus-circle"
                                        }),
                                    className: "btn btn-info m-2",
                                    disabled: counter.value === 0,
                                    onClick: (function (param) {
                                        Curry._1(onDecrement, counter);
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx("i", {
                                          "aria-hidden": true,
                                          className: "fa fa-trash-o"
                                        }),
                                    className: "btn btn-danger",
                                    onClick: (function (param) {
                                        Curry._1(onDelete, counter.id);
                                      })
                                  })
                            ],
                            className: ""
                          })
                    ],
                    className: "row"
                  })
            });
}

var make = Counter;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
