// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Navbar from "./components/navbar.bs.js";
import * as Counters from "./components/counters.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return [
                {
                  value: 0,
                  id: 1
                },
                {
                  value: 0,
                  id: 2
                },
                {
                  value: 0,
                  id: 3
                },
                {
                  value: 0,
                  id: 4
                }
              ];
      });
  var setCounters = match[1];
  var counters = match[0];
  var handleIncrement = function (counter) {
    Curry._1(setCounters, (function (prev) {
            return prev.map(function (c) {
                        if (c.id !== counter.id) {
                          return c;
                        } else {
                          return {
                                  value: c.value + 1 | 0,
                                  id: c.id
                                };
                        }
                      });
          }));
  };
  var handleDecrement = function (counter) {
    Curry._1(setCounters, (function (prev) {
            return prev.map(function (c) {
                        if (c.id !== counter.id) {
                          return c;
                        } else {
                          return {
                                  value: c.value - 1 | 0,
                                  id: c.id
                                };
                        }
                      });
          }));
  };
  var handleDelete = function (counterId) {
    Curry._1(setCounters, (function (prev) {
            return prev.filter(function (c) {
                        return c.id !== counterId;
                      });
          }));
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("main", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx(Navbar.make, {
                                  totalCounters: counters.filter(function (c) {
                                          return c.value > 0;
                                        }).length.toString()
                                }),
                            JsxRuntime.jsx(Counters.make, {
                                  onReset: (function (param) {
                                      Curry._1(setCounters, (function (prev) {
                                              return prev.map(function (c) {
                                                          return {
                                                                  value: 0,
                                                                  id: c.id
                                                                };
                                                        });
                                            }));
                                    }),
                                  onIncrement: handleIncrement,
                                  onDelete: handleDelete,
                                  onDecrement: handleDecrement,
                                  counters: counters,
                                  onRestart: (function (param) {
                                      window.location.reload();
                                    })
                                })
                          ],
                          className: "card__box"
                        }),
                    className: "container"
                  }),
              className: "main__wrap"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
