// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './index.css'
;

import 'bootstrap/dist/css/bootstrap.css'
;

import 'font-awesome/css/font-awesome.css'
;

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(App.make, {}));
}

export {
  
}
/*  Not a pure module */
